import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/daohomegenerator">DAOHOMEGENERATOR</Link>
        </li>
        <li>
          <Link to="/daoselecttesnet">DAOselecttesnet</Link>
        </li>
        <li>
          <Link to="/nameservice">NameService</Link>
        </li>
        <li>
          <Link to="/nameservicedefinefunctionality">
            Nameservicedefinefunctionality
          </Link>
        </li>
        <li>
          <Link to="/frame371686">Frame371686</Link>
        </li>
        <li>
          <Link to="/daodefinemultisigmembersone">
            DAOdefinemultisigmembersOne
          </Link>
        </li>
        <li>
          <Link to="/daodefinemultisigmembers">DAOdefinemultisigmembers</Link>
        </li>
        <li>
          <Link to="/daoresulta">DAOresulta</Link>
        </li>
        <li>
          <Link to="/daowaitingforconfirmationb">
            DAOwaitingforconfirmationb
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
